### PR TITLE
Feature/branding palette

### LINKED ISSUE #21: Use branding colors to create theme palettes
#### Describe the desired behavior
I want our branding colors to be used to create new themes.  

#### Describe the current behavior
If you try to use the `mat-palette` function in angular projects, the build will fail due to a missing contrast value.

#### Is this request related to a current issue?
No

#### Additional Context
Demo showing current workaround: https://stackblitz.com/github/emclaug2/checkbox-theme-demo

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #21 

#### Changes proposed in this Pull Request:
- Add reasonable contrast palette so brand-color palettes can be integrated into angular apps.

### CODE REVIEW

**Comment by huayunh** [comment]
How were those colors decided? I assume that you plug those colors in some contrast checker to maximize the contrast?

**Review by joebochill — COMMENTED** [review]
Our UI Color palette just uses `contrastDefaultColor` with a value of 'light' or 'dark'. I assume this is more granular because some shades need a dark and some need a light? Should we say 'dark' and 'light' instead of hardcoding black and white? How do these contrast colors get used in the theme?

**Comment by emclaug2** [comment]
> Our UI Color palette just uses `contrastDefaultColor` with a value of 'light' or 'dark'. I assume this is more granular because some shades need a dark and some need a light? Should we say 'dark' and 'light' instead of hardcoding black and white? How do these contrast colors get used in the theme?

I read some of this [article](https://medium.com/@tomastrajan/the-complete-guide-to-angular-material-themes-4d165a9d24d1)  and this was the insightful:

"It can be useful to retrieve appropriate contrast color when using main color as a background for some component which also contains text. In that case we can retrieve corresponding contrast color, eg: mat-color($primary, lighter-contrast) for backgrounds which mat-color($primary, lighter)."

**Comment by emclaug2** [comment]
> How were those colors decided? I assume that you plug those colors in some contrast checker to maximize the contrast?

I just went into this color picker and looked for the tipping point when black or white provides a higher contrast.
https://contrast-ratio.com/#black-on-%23e88b14

I just pushed out a fix for any colors that weren't using the correct contrast.

**Comment by emclaug2** [comment]
>  Should we say 'dark' and 'light' instead of hardcoding black and white? How do these contrast colors get used in the theme?

What I did was update the branding colors so they could be used in the angular themes, our @pxblue/colors palette.scs also has a contrast section in each color..

I'm not sure how the `light` or `dark` attribute is used, but it doesn't seem like it's required since it' an optional param.  I'm unfamiliar with what that attribute does in non-angular projects.

**Comment by joebochill** [comment]
> > Should we say 'dark' and 'light' instead of hardcoding black and white? How do these contrast colors get used in the theme?
> 
> What I did was update the branding colors so they could be used in the angular themes, our @pxblue/colors palette.scs also has a contrast section in each color.
> 
> I'm not sure how the `light` or `dark` attribute is used, but it doesn't seem like it's required since it' an optional param. I'm unfamiliar with what that attribute does in non-angular projects.

👍 I was looking it the colors.ts file...forgot we have different files for angular and react.

**Review by joebochill — APPROVED** [review]

**Comment by joebochill** [comment]
This looks good to me if you just want to update the publish date (maybe to tomorrow depending on how fast you think you can get two approvals on a master PR)

**Comment by emclaug2** [comment]
I'm going to try to publish these changes today.  I've updated the changelog for today's date.

**Pull request merged**
